namespace: "epfl_si"
name: "actions"
version: "0.2.0"
readme: "README.md"
authors:
    - "EPFL IDEV-FSD <idev-fsd@groupes.epfl.ch>"
license:
    - "MIT"
tags:
    - actions
repository: "https://github.com/epfl-si/ansible-collection-actions"
